# Generated by Django 5.1.2 on 2024-10-24 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiCRUD', '0002_alter_goal_autore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='autore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiCRUD.autore', to_field='uuid'),
        ),
    ]
